# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "catalogai-optimizer"
client_id = "18d643b75cf05db561e4883f7a2ef108"
application_url = "https://catalogai-optimizer-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory,write_metafields,read_orders"

[auth]
redirect_urls = [
  "https://catalogai-optimizer-production.up.railway.app/auth/callback",
  "https://catalogai-optimizer-production.up.railway.app/auth/shopify/callback",
  "https://catalogai-optimizer-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"
